### ISSUE TITLE
Separação do Front End (VueJs) do Back End (Laravel)

### ISSUE THREAD

**Issue by oraphaBorges** [practice-uffs/mural#265]
O Front End do Mural atualmente está híbrido entre o Lavel e o VueJs. Esses projetos devem ser separados de forma que tudo que estiver relacionado ao Front End seja de exclusividade do Vue e tudo que for de Back End seja de exclusividade do Laravel.

**Comment by CleissonVieira** [comment]
Informei a tag Mural V2, pois as issues com essa tag serão preparadas para a segunda versão refatorada pelo @Dovyski 
Nessa versão eu vejo que seria interessante não termos mais a API juntamente ao Mural
