### ISSUE TITLE
Reunião de troca de conhecimento

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#297]
@practice-uffs/dev 
Reunião aconteceu no dia 15/05 das 21h às 23h, acordado via doodle.

De grande valia foi a vídeo chamada, onde o @oraphaBorges desenvolveu atividades do Mural compartilhando sua tela e explicando o fluxo que estava desenvolvendo. Os demais que estavam assistindo acompanharam e tiraram sua dúvidas, tanto do desenvolvimento do Rapha quanto sobre os seus próprios desenvolvimentos em outras tarefas.

Além da gravação que ficará disponível, sendo possível retomar o que foi desenvolvimento para um melhor entendimento, esse formato de reunião ofereceu mais entrosamento e troca de conhecimento entre a equipe.

Foi decidido realizar mais reuniões como está, que foram chamadas de KT - Knowledge Exchange no Português Troca de Conhecimento, sendo tratado outros temas nas próximas. A ideia foi uma vez por semana durante 1 hora.

Ideias para próximas reuniões KT:
- Postman;
- Microserviços;
- Métodos Ágeis;
- DevOps e integrações continua;
- Testes (conceito);
- Boas práticas;
- Refatoração;
- Dívida técnica.

Minha opinião seria realizar essas trocas de conhecimento de acordo com nossa prioridade.
No momento essa prioridade seria em cima dos novos integrantes entenderem melhor do sistema do Web-feedback, onde nossas demandas tem prioridades.

Todas as KTs precisam ser relacionadas a assuntos que possam acrescentar nesse sentido. Quando a prioridade mudar ai nos adaptamos. Dessa forma conseguimos ser mais produtivos.

O @alissonpeloso ficou como responsável pela edição da gravação dessa reunião.
Assim que concluir por gentileza realizar upload da mesma [nessa pasta do drive](https://drive.google.com/drive/u/2/folders/18B93CnCBwTV-Npe8RLVB26qZKEs40mG9) e sinalizar nesta issue.

Issue destinada a dúvidas e sugestões.

**Comment by alissonpeloso** [comment]
Vídeo upado [aqui](https://drive.google.com/drive/u/0/folders/18B93CnCBwTV-Npe8RLVB26qZKEs40mG9)
