### ISSUE TITLE
Reset Banco

### ISSUE THREAD

**Issue by oraphaBorges** [practice-uffs/mural#300]
Por conta da alteração da estura do banco pela issue #281 tanto os banco de teste e produção devem receber o migrate com as alterações. Mas aproveitar para resetar ambos com

```
php artisan migrate:refresh
php artisan db:seed
```

**Comment by oraphaBorges** [comment]
isso já resolveria a issue #286 também!

**Comment by CleissonVieira** [comment]
Com o Mural V2 existira novas funcionalidades e acredito que será realizado esse processo. No banco do dev foi realizado o processo.
