### ISSUE TITLE
Prazo de avaliação de demanda

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/mural#304]
Durante a reunião de equipe da @practice-uffs/con-midia, percebemos a importância de esclarecer aos solicitantes que precisamos de um prazo para avaliar se a demanda é viável e se conseguiremos atende-la.

Pensamos que essa informação pode estar junto ao prazo do solicitação de produto, que atualmente é variável. Por exemplo: "Composição de vídeos / Prazo variável / Prazo de avaliação de demanda: 3 dias úteis"

Entendemos a necessidade desse prazo de avaliação de demanda (3 dias úteis) para todos os serviços e produtos do mídia, mas pode ser que outras equipes queiram aproveitar o recurso, o que podemos discutir em uma reunião de líderes.

**Comment by CleissonVieira** [comment]
Informei uma tag para discutir na próxima reunião de lideres, assim que definido atualizamos a issue com a certeza do que precisa ser feito hehe

**Comment by CleissonVieira** [comment]
Analisando o mural como está nesse momento, junto com a demanda, inclui está tarefa para uma Sprint futura junto as demais tarefa para uma segunda versão do Mural. 

Onde acredito que por padrão ao criar uma Solicitação o cliente receba uma mensagem onde a solicitação permanecerá 3 dias em análise, independente do tipo do serviço, para avaliar a viabilidade. Para prosseguir o uso do mural o cliente será obrigado a clicar em um botão para "confirmar  leitura" sobre os 3 dias úteis.

**Comment by Dovyski** [comment]
Implementado no mural `v2`. Essa configuração pode ser editada por cada equipe no painel de administração de serviços.
