### ISSUE TITLE
Alterações na hora de pedir serviços

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/mural#323]
Eu achei que seria muito trabalhoso explicar o que eu queria mostrar, então eu resolvi gravar um vídeo para explicar. Vou deixar o vídeo disponível em algum lugar. 

**O vídeo está [nesta pasta](https://drive.google.com/drive/u/5/folders/1sgoXrHIIXnMZfg4GS7Tm3uSe-cWC-8B7).**

**Comment by Dovyski** [comment]
Implementado no mural `v2`.
