### ISSUE TITLE
Problema na solicitação de serviço no Mural

### ISSUE THREAD

**Issue by GessicaZanon** [practice-uffs/mural#335]
**Problema**
Tentei fazer uma solicitação de serviço pelo mural, entretanto, não estou conseguindo. O problema parece estar nos tipos de serviço e especificações dos serviços. Algumas opções não estão nem aparecendo, como "cartaz" e "outros" por exemplo.

**Etapas para reproduzir o problema:**
1. Vá para 'https://mural.practice.uffs.cc/servicos/solicitar'
2. Clique em 'Solicitar Serviço'
3. Clique em 'Tipo de Serviço'
4. Clique no segundo tipo de serviço 'imagem'
5. Em especificações do serviço, pede para que seja selecionado algum item, entretanto, não aparece nenhum item, e assim o sistema não permite que eu envie minha solicitação de serviço 

**Comportamento esperado**
Espera-se que apareçam as opções para que alguma seja selecionada, inclusive a opção "outros"

**Desktop (preencha as seguintes informações):**
  - Sistema operacional: Windows
  - Versão do sistema operacional: 10
  - Navegador: Chrome
  - Versão do navegador: 91.0.4472.124 (Versão oficial) 64 bits

**Comment by CleissonVieira** [comment]
Situação não ocorre mais.
