### ISSUE TITLE
Adequação nas descrições de produtos e serviços (Con-Mídia)

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/mural#336]
A equipe @practice-uffs/con-midia sente a necessidade de ter as descrições dos produtos e serviços ofertados pela equipe readequados. Trabalhamos em um [documento](https://docs.google.com/document/d/1gXx4wpcmDODUOnrTmdz8xLQ0J3-5RWKF3jGOVg6pZr0/edit) coletivo a fim de reescreve-las e pedimos, gentilmente, que façam a alteração no mural. 

Aproveitamos para organizar os serviços em novas categorias e subcategorias, com suas respectivas descrições. 
Ficamos a disposição caso surja alguma dúvida.

**Comment by CleissonVieira** [comment]
Agora os produtos vão ser criados do 0, não há mais a necessidade da alteração
