### ISSUE TITLE
Mural V2: Funcionamento errado na filtragem por status dos pedidos

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/mural#351]
A filtragem por status dos pedidos não funciona adequadamente:
  - status "Em andamento" mostrando as já encerradas
  - status "Finalizado" mostrando as que estão em andamento

Aparentemente está com a mesma filtragem para os dois casos (mostrar todos os status)

**Comment by Dovyski** [comment]
Corrigido em 32ecc94.
