### ISSUE TITLE
Mural V2: Vinculação da tarefa nas pastas do Drive não está operacional

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/mural#352]
Ao criar a Issue no github e vincular a mesma no Mural, as pastas criadas para a tarefa no Drive não ficam disponíveis no Mural

**Comment by lcaimi** [comment]
Outro efeito é que todos pedidos possuem um arquivo vinculado chamado banner.png. Possivelmente é alguma vinculação subjascente no Drive

**Comment by Dovyski** [comment]
Corrigido :shipit:
