### ISSUE TITLE
Exibir detalhes do serviço na tela de /servicos/solicitar/#

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#355]
No mural V2, na listagem de serviços, cada serviço tem sua especificação. Porém ao clicar em solicitar, abre o formulário para realizar a solicitação, não possui essas especificações.

**Objetivo:** na tela do /servicos/solicitar/# (print abaixo) retornar as informações do serviço (prazos de avaliação, de execução e descrição)

![image](https://user-images.githubusercontent.com/29258164/129104003-3656c68b-7a44-4f6d-b750-9488b308040e.png)

**Comment by Dovyski** [comment]
Implementado em 903e25f.
