### ISSUE TITLE
Alterar texto de "Situação" conforme Status do pedido

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#358]
Após o administrador alterar o status de um pedido, o texto da placa de "SITUAÇÃO" se mantem o mesmo. Em alguns casos verifiquei que a cor alterou de amarelo para verde. Outros testado no mesmo instante se manteve a mesma cor e texto.
Os status de situação na listagem de pedidos está em inglês, seria interessante alterar a cor como melhoria para UX / UI.
Verificar imagem abaixo.

**Objetivo:** 
- [ ] alterar texto de "Situação", nas especificações de um pedido / solicitação (["/servico/#"](https://v2.mural.practice.uffs.cc/servico/6)) para se tornar dinâmico conforme "status desse pedido";
- [ ] traduzir status de "Situação" na listagem de pedidos (["/gerenciar/pedidos'](https://v2.mural.practice.uffs.cc/gerenciar/pedidos)) e solicitações (["/servicos/acompanhar"](https://v2.mural.practice.uffs.cc/servicos/acompanhar))

![image](https://user-images.githubusercontent.com/29258164/129107728-e7e5c351-6f05-4dd9-bd49-7dc858824705.png)

![image](https://user-images.githubusercontent.com/29258164/129107781-97d274d1-d193-4f6f-9c70-5b7ff4ebba20.png)

![image](https://user-images.githubusercontent.com/29258164/129107970-d43979a7-ede1-46da-9ccd-58953f588f24.png)

**Comment by Dovyski** [comment]
Corrigido! :shipit:
