### ISSUE TITLE
Exclusão de uma categoria já existente 

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/mural#363]
**Descreva o bug/problema:**

Exclui uma categoria de serviço que já estava sendo "utilizada" e então as páginas de serviços e pedidos não abriram normalmente. A mensagem de erro: "ErrorException
Trying to access array offset on value of type null (View: /home/practicemuralv2/v2.mural.practice.uffs.cc/resources/views/livewire/admin/orders.blade.php)"

**Comportamento esperado:**

Acredito que era pra ser possível excluir uma categoria de serviço, que automaticamente todos os serviços relacionados àquela categoria seriam excluídos também, ou ficaria com o espaço de "categoria" em branco.

**Capturas de tela:**

![Captura de Tela (99)](https://user-images.githubusercontent.com/71669689/129749615-c63ced15-fe53-471b-8926-bf69652e80eb.png)

**Comment by Dovyski** [comment]
Oh, glória. Obrigado, @robisonjose !

**Comment by Dovyski** [comment]
Corrigido em 477f548.
