### ISSUE TITLE
Acesso ao drive a partir do Github inacessível

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/mural#365]
Os usuários não tem permissão de acesso as pastas criadas  no drive, adepois que uma atividade é criada na mural e o Bot cria as pastas (que fica inacessível).

**Comment by Dovyski** [comment]
Corrigido em fdaead1. Pasta do drive já criadas pelo mural não são afetadas, então é necessário fazer uma solicitação nova para que a correção tenha efeito.
