### ISSUE TITLE
Aumentar tempo utilizado no aplicativo para expirar token

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#369]
O tempo do token de login utilizado no aplicativo está localizado no Mural.
Esse ajuste foi realizado no Mural V1.

Necessário aumentar o tempo que o token expira.
[Clique para ver tarefa no V1](https://github.com/practice-uffs/mural/issues/362)

**Comment by Dovyski** [comment]
Corrigido em 1543f99.
