### ISSUE TITLE
Bug de layout na pagina /mural/gerenciar/pedidos

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#371]
[/mural/gerenciar/pedidos](https://v2.mural.practice.uffs.cc/gerenciar/pedidos)
---

Para smartphone:
- [x] Se título e comentário for grande uma parte é cortada;
- [x] Local e Datas não aparece;
- [x] Área de filtro desconfigura

![image](https://user-images.githubusercontent.com/29258164/131571327-aab917f9-55bf-4a70-ad87-48fb47d616d3.png)

Para dimensões de computador:
- [x] Comentários, se muito grandes, são cortados;

![image](https://user-images.githubusercontent.com/29258164/131571417-49071ab2-33d3-49e1-b4db-df2d43bfbce0.png)

**Comment by Dovyski** [comment]
Corrigido em 446eb7e.
