### ISSUE TITLE
Menu desaparece para dispositivos móveis

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#372]
- [x] Dispositivos com dimensões menores que **990x** (apenas o valor anterior ao X importa) o menu está desaparecendo.
- [x] Dispositivos com dimensões entre **991x** e **1180x** o logo "Mural" está sobreponto o botão "Inicial"

![image](https://user-images.githubusercontent.com/29258164/131574126-03636013-c209-45ab-8a15-d9c80d7af140.png)

![image](https://user-images.githubusercontent.com/29258164/131573826-f6f5a2b1-8b47-4a8f-aba3-953cfa4bf9d4.png)

**Comment by Dovyski** [comment]
Corrigido em c12b633.
