### ISSUE TITLE
Bug de layout na pagina /gerenciar/servicos/servicos

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#373]
[/gerenciar/servicos/servicos](https://practice.uffs.edu.br/mural/gerenciar/servicos)
---

- [x] A tabela com listagem dos serviços existentes não está responsiva, quanto menor as dimensões da tela menos colunas aparece, ou corta os dados.

![image](https://user-images.githubusercontent.com/29258164/131579471-b62d91cb-45eb-4c05-8753-f80a3e93e63e.png)

**Comment by Dovyski** [comment]
Corrigido em e30e48e01a9872cbe62b385be32b8d9ef66cbc80.
