### ISSUE TITLE
Envio de notificação com o FireBase

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#374]
Envio de notificação com o FireBase ao modificar estado da solicitação e comentário 
Tarefa #342 feita no Mural V1 
[Pull Request](https://github.com/practice-uffs/mural/pull/348) feito no Mural V1 dessa tarefa

**Comment by Dovyski** [comment]
Essa tarefa depende de https://github.com/practice-uffs/api/issues/11.

**Comment by CleissonVieira** [comment]
Tarefa [practice-uffs/api/issues/11](https://github.com/practice-uffs/api/issues/11) concluida
Da para seguir a implementação desta tarefa

**Comment by CleissonVieira** [comment]
@alissonpeloso se puder dar uma estudada nessa tarefa para nós implementar
Na reunião de quarta-feira conversamos sobre se precisar
