### ISSUE TITLE
 Envio de E-mail ao realizar uma ação

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#375]
Envio de E-mail ao criar uma solicitação, alteração de estado da solicitação, comentário na solicitação, etc.
 
 Tarefa já implementada no Mural V1 
 [Pull Request](https://github.com/practice-uffs/mural/pull/308) no V1

**Comment by Dovyski** [comment]
E-mails para alteração de estado e comentários já estão implementados. O envio de e-mail ao criar uma solicitação foi implementado em 4325d5c.
