### ISSUE TITLE
Data de entrega mínima

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#376]
Na dev tem um limite de tempo pra sugestão de data de entrega de serviço (foi utilizado 10 dias lá) | obs: Apenas a parte do formulário de solicitação de serviço.

Tarefa realizada no V1: #357 
[Pull request](https://github.com/practice-uffs/mural/pull/325) da implementação no V1

**Comment by Dovyski** [comment]
Corrigido em 3ce2629.
