### ISSUE TITLE
Tela de solicitação de serviços: ordem de apresentação dos serviços

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/mural#377]
A tela de solicitação de servições está listando os serviços pelas áreas sem considerar o volume de demandas que recebemos.

Minha sugestão é criar uma "categoria" chamada principais serviços (ou outro nome) e colocar os serviços mais utilizados. Na apresentação da tela esta categoria aparece primeiro na tela.

Cada equipe pode eleger os serviços que devem aparecer nesta categoria.

Obs: mesma situação no Aplicativo

**Comment by Dovyski** [comment]
Gostei bastante dessa ideia! Eu acho que podemos inclusive colocar, além da ordem, um indicativo do tipo "popular" ou coisa parecida.

**Comment by Dovyski** [comment]
A ideia é colocar uma categoria (mostrador) para os serviços mais populares.

**Comment by Dovyski** [comment]
Implementado em 62094a1.

![image](https://user-images.githubusercontent.com/512405/132847119-c2d76172-474a-497d-9528-555235ec7b92.png)
