### ISSUE TITLE
Treinamento Mural V2

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#378]
Olá galerinha do Github

Pessoal, [segue link do doodle](https://doodle.com/poll/s8z4m2m7vgmnufs7?utm_source=poll&utm_medium=link) com horários para semana que vem realizarmos o treinamento para os líderes em cima do Mural Versão 2

@practice-uffs/lideres

**Comment by MilenaPaz2020** [comment]
Respondido!

**Comment by GessicaZanon** [comment]
Respondido!

**Comment by morgana-mo** [comment]
Respondido 😁

**Comment by CleissonVieira** [comment]
Pessoal, ficara em aberto até sexta a noite.  
Sinta-se a vontade a convidar os integrantes de suas equipes a participar desse treinamento. Basta compartilhar o link.
Porém, a preferência da data para esse treinamento é aquela que o máximo, ou todos, os líderes possam participar.

**Comment by MilenaPaz2020** [comment]
> Pessoal, ficara em aberto até sexta a noite.
> Sinta-se a vontade a convidar os integrantes de suas equipes a participar desse treinamento. Basta compartilhar o link.
> Porém, a preferência da data para esse treinamento é aquela que o máximo, ou todos, os líderes possam participar.

Obrigada, @CleissonVieira! Peço, gentilmente, que o treinamento seja gravado. Assim, quem não conseguir participar pode assistir depois. Grata.

**Comment by CleissonVieira** [comment]
Pessoal, informativo então sobre o treinamento para o Mural V2:
- Os 3 dias que a maioria das pessoas podem participar, infelizmente nenhum deles a Luiza vai poder;
- Precisamos de alguém para gravar o treinamento, então disponibilizamos aos demais, conforme @MilenaPaz2020 solicitou;

Dias com o mesmo número de votos e mais votados:
- Segunda-feira, 13/09 das 16:30h às 17:30h;
- Quinta-feira, 16/09 das 16:30h às 17:30h;
- Quinta-feira, 16/09 das 17:30h às 18:30h;

A minha opinião é o quanto antes realizar esse treinamento, então fica definido para:
- Segunda-feira, 13/09 das 16:30h às 17:30h;

**Comment by CleissonVieira** [comment]
### Fluxos Mural V2:

#### 1. ADM -> Categorias
Utilizado para incluir e dividir os serviços
Cadastro:
- Nome
- Abreviação
- Descrição
- `Aviso (ainda não está em uso este campo)`
- Cor (valor referente a intensidade da cor)
- Ativa (ativa/desativa a categoria e serviços inclusos a mesma)


#### 2. ADM -> Locais
Utilizado para definir a localidade a qual o serviço está sendo solicitado
Cadatro:
- Nome
- Sigla
- Descrição
- Ativo (ativa/desativa a listagem de locais no cadastro de serviços)


#### 3. ADM -> Serviços
Utilizado para criar os serviços disponíveis em **Solicitar serviço**
Todas as informações abaixo são editáveis após criação (no momento não deletar serviços)
Cadastro:
- Categoria (áudio, vídeo,
- Nome
- Descrição
- Dias úteis (referente ao prazo para entrega após período de avaliação)
- Dias úteis para avaliação (prazo para avaliar a demanda)
- Aviso (destacado abaixo do botão de **SOLICITAR**)
- Cor (referente ao ícone, quanto maior mais intensa a cor)
- Ícone (topo do card de solicitação)
- Perguntas adicionais (ao solicitar o serviço) `adicionar inserção de imagens`
- Disponível (ativa/desativa o botão **SOLICITAR** ao usuário)
- Ativo (ativa/desativa a listagem nos serviços)


#### 4. ADM -> Usuários
Utilizado para verificar todos os membros cadastrados, que já acessaram o Mural, e também gerenciar os privilégios da conta.
Campos editáveis:
- Nome
- E-mail
- Username (utilizado para acesso)
- Privilégio (permissão que terá)


#### 5. ADM -> Newsletter
Usuários que se inscreveram na **NOSSA NEWSLETTER** disponível no rodapé do Mural.
Campos editáveis:
- E-mail
- `Data de inscrição (necessário ocultar)`


#### 6. CLIENTE -> Ideia
Destinado ao usuário enviar suas ideias ao PRACTICE.
 `Interessante o usuário verificar suas próprias ideias`
 `Interessante criar listagem de ideias no painel de ADM`

#### 7. CLIENTE -> Feedback
Espaço destinado a feedbacks de usuários ao PRACTICE.
 `Interessante criar pagina de feedbacks no painel de ADM`
 
#### 8. CLIENTE -> Solicitar serviço
Utilizado para o usuário realizar uma solicitação a equipe do PRACTICE.
- Busca a solicitação desejada
- Se disponível: clica em **SOLICITAR**
- Preenche os campos: Título, Descrição, Local, Prazo de entrega sugerido e campos adicionais (caso existam)
- Clica em enviar e seu serviço é encaminhado a equipe do PRACTICE.

#### 9. CLIENTE -> Acompanhar serviços
Página destinada ao usuário acompanhar suas solicitações.
Nela é possível:
- Interagir com atendentes através de comentários e arquivos
- Visualizar todos os dados inseridos
- Acompanhar status e situação

#### 10. ADM -> Pedidos
Página destinada aos Atendentes gerenciarem as solicitações dos usuários.
Nela é possível:
- Interagir com os solicitantes através de comentários e arquivos
- Alterar status/situação
- Acrescentar/acompanhar a tarefa no github

**Comment by GessicaZanon** [comment]
Gravação do treinamento [nessa pasta](https://drive.google.com/drive/u/0/folders/1agycP1W7-XtO8RrIln7owX-as4D79deS), galerinha!
