### ISSUE TITLE
Erro ao deletar serviço 

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#380]
Ao testar o mural V2 segui os seguintes fluxos:
1. Criei um Serviço X;
2. Realizei uma solicitação do serviço X;
3. Deletei o serviço X;
4. Acessei a página ADM -> pedidos
5. Gerou o erro nas imagens abaixo.

Acredito que seja porque a solicitação estava ligada ao serviço, após ser deletado ele não encontrou essa dependência e gerou erro. 
Seria interessante ao em vez de deletar o Serviço criar uma aba de **Serviços arquivados** e alterar o botão para arquivar.

![image](https://user-images.githubusercontent.com/29258164/133008178-dce12128-722f-461d-9e31-2963ac5c5d10.png)
![image](https://user-images.githubusercontent.com/29258164/133008173-057cf23c-76c8-42d8-8d00-3d2a8570af01.png)
![image](https://user-images.githubusercontent.com/29258164/133008195-76b0c06f-af23-4b87-b7c2-3cb4562eba19.png)

**Comment by Dovyski** [comment]
Corrigido em 6bb2d83.
