### ISSUE TITLE
Prazo de entrega sugerido.

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/mural#381]
Como comentado na reunião do mural V2:

O prazo de entrega sugerido do serviço (aquele que o solicitante vai colocar) deve ser, no mínimo, a soma dos nossos prazos. Por exemplo: Se o nosso prazo total for de 15 dias úteis e o solicitante pedir o produto dia 1, ele só poderá marcar o prazo de entrega sugerido para no mínimo, dia 16.

**Comment by CleissonVieira** [comment]
As funções utilizadas na implementação do Mural não permite fazer essa soma de datar no momento.
Vamos manter limitado a, pelo menos, 10 dias após a data de criação da solicitação para o usuário selecionar a possível data de entrega.

Deixa está tarefa em aberto para futuramente encontrarmos uma maneira de realizar este ajuste.
