### ISSUE TITLE
Links quebrados e outros problemas

### ISSUE THREAD

**Issue by lcaimi** [practice-uffs/mural#383]
Relato de alguns problemas nos links do Mural V2.

---
#392 <s>
No rodapé da página os links de divulgação estão todos apontando para materias que se encontram no servidor https://cdn.uffs.cc/practice/website/marketing/

No rodapé alguns links para redes sociais estão quebrados
- Github 
  Quebrado: https://github.com/practiceuffs
  Correto: https://github.com/practice-uffs
- Instagram
  Quebrado: https://www.instagram.com/practice-uffs/
  Correto: https://www.instagram.com/practiceuffs/
</s>

---

No menu Ideias
 - Para mim a "Dica: clique na lâmpada ao lado para ver uma ideia" não faz sentido considerando que as idéias já estão deslizando na tela. Sugiro algo do tipo "Clique na lâmpada se tiver uma ideia para compartilhar" e com isto a lâmpada acende e vai para a região da página onde pode ser preenchido o form.

 No menu Feedback
 - Quando o usuário não seleciona nenhuma das opções a mensagem apresentada é: "O campo data.type é obrigatório"
Sugiro "O campo Tipo é obrigatório"

No menu Acompanhar serviço
- Na visão geral da lista de pedidos a situação está mostrando os valores em inglês (todo, review, doing, etc). Acho que deveria ser em Português
- Quando o solicitante insere um arquivo ele fica registrado como inserido pelo Fernando Bevilacqua (trocar para Practice UFFS)
- A mensagem abaixo do comentário diz "Você pode usar markdown para formação." Acho que deveria ser "Você pode usar markdown para formatação." 
- Nesta mesma mensagem talvez seja interessante o link para algum tutoria de markdown (pode ser do próprio GitHub)

No Menu Admin -> Serviço -> Editar
- Não é possivel colocar nenhum valor no campo ordem (para colocar como popular). Dá erro no processamento do do SQL

#393
No Menu Admin -> Pedidos
- A seleção de serviços pelo Status não está plenamente operacional

**Comment by isabelirk** [comment]
PS: o PRACTICE possui dois canais no YouTube, atualmente está linkado o canal de lives.

**Comment by isabelirk** [comment]
PS: a página admin > pedidos não está funcionando (link quebrado).

**Comment by CleissonVieira** [comment]
Estou mapeando e criando outras tarefas.
Por este motivo estou tachando os textos.

**Comment by CleissonVieira** [comment]
> PS: a página admin > pedidos não está funcionando (link quebrado).

Está acessando o site para testes Isa, testa com essa URL: <https://practice.uffs.edu.br/mural/>
