### ISSUE TITLE
Verificação de leitura na solicitação

### ISSUE THREAD

**Issue by mariagelain** [practice-uffs/mural#385]
É necessário criar um meio de termos uma confirmação de visualização de leitura (ou de acesso) do solicitante ao abrir a demanda que teve atualização (ou as demandas, caso for mais de uma).

**Comment by Dovyski** [comment]
![image](https://user-images.githubusercontent.com/512405/135512401-d5b43d37-971b-4ecf-8adf-66afba9a7f6a.png)

Implementado! 🚀
