### ISSUE TITLE
ajuste no rodapé

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/mural#386]
No rodapé do mural v2, no item "divulgação", sugiro alterar a ordem dos serviços para:

- visão geral (aqui sugiro alterar a frase para algo do tipo: conheça o PRACTICE)
- serviços de áudio
- serviços de conteúdo
- serviços de eventos online
- serviços de estúdio

![muralV2-ajuste1](https://user-images.githubusercontent.com/31291959/133614386-d503c204-0bb4-48e2-8d56-219a7ef2d27e.png)

**Comment by CleissonVieira** [comment]
Criei uma nova tarefa para mapear todas as issues relacionadas ao footer 
#392
