### ISSUE TITLE
ajuste na página "acompanhar serviços"

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/mural#387]
Sugiro adicionar um botão para abrir solicitação para o caso do usuário que entrar na página "acompanhar serviços" e não tiver nenhuma solicitação aberta no momento.

![muralV2-ajuste2](https://user-images.githubusercontent.com/31291959/133615964-b868343c-01bc-4c9b-8ff7-38da0d2519c9.png)

**Comment by Dovyski** [comment]
Implementado em 2fa1049.
