### ISSUE TITLE
Menu Admin -> Serviços

### ISSUE THREAD

**Issue by isabelirk** [practice-uffs/mural#390]
- [x] Não é possível colocar nenhum valor no campo ordem (para colocar como popular) ao editar um serviço. Dá erro no processamento do SQL;
- [x] trocar a ordem da posição dos campos "dias úteis" e "dias úteis para avaliação";
- [x] adicionar uma breve descrição do que deve ser preenchido em cada campo (colocar um símbolo de interrogação ao lado do nome do campo, e quando colocar o mouse em cima aparecer uma janela explicando o que é o campo);
- [x] Existe campos obrigatórios? Eles precisam ser sinalizados... (caso a resposta seja sim, verificar a existência deles nos outros formulários do site também).

![muralV2-ajuste7](https://user-images.githubusercontent.com/31291959/133621833-97405d3b-16e2-4376-b394-145930db70be.png)

**Comment by Dovyski** [comment]
Excelentes sugestões de UI/UX, @isabelirk ! Tudo foi implementado em e8b50c4.
