### ISSUE TITLE
Refactory footer

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#392]
- [x] No rodapé da página os links de divulgação estão todos apontando para materiais que se encontram no servidor https://cdn.uffs.cc/practice/website/marketing/ (possibilidade: usar encurtador de URL para não mostrar a URL do servidor)
---
- [x] Correção do link do instagram e github do PRACTICE no rodapé e adicionar _blank nos links para abrir nova página quando clicado.
**Links corretos:**
- github: https://github.com/practice-uffs
- instagram: https://www.instagram.com/practiceuffs/
---
- [x] No rodapé do mural v2, no item "divulgação" alterar a ordem dos serviços para:
- visão geral (alterar a frase para algo do tipo: conheça o PRACTICE)
- serviços de áudio
- serviços de conteúdo
- serviços de eventos online
- serviços de estúdio
---
- [x] No rodapé o link **Esse software é open-source e gratuíto** direciona para uma página inexistente, corrigir ou remover.

**Comment by Dovyski** [comment]
Implementado em dd68ead.
