### ISSUE TITLE
No Menu Admin -> Pedidos

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#393]
A seleção de serviços pelo Status não está plenamente operacional
Ou os a listagem de status está incorreta na listagem de Pedidos

![image](https://user-images.githubusercontent.com/29258164/133716526-76e61d22-6dbe-46ab-9cba-c947412b0da6.png)

**Comment by Dovyski** [comment]
Corrigido em dd68ead5354197ad36cffaec1b975c46c778056e.
