### ISSUE TITLE
Vincular pastas de entrada e saída ao Mural V2

### ISSUE THREAD

**Issue by MilenaPaz2020** [practice-uffs/mural#398]
Esse problema já tinha sido comentado, mas abro a issue para não esquecer.

Os docs encaminhados pelo solicitante no mural não aparecem na pasta de entrada da issue. O mesmo ocorre quando subimos um arquivo na pasta de saída da issue, ele não aparece para o cliente no mural.

**Comment by CleissonVieira** [comment]
Em testes, identifiquei que ao encaminhar arquivos na pasta do drive destinada ao cliente (onde o arquivo é feito upload para pasta Entrada), a imagem é listada nas enviadas na solicitação do Mural, porém no drive não é enviado.
Verifiquei na pasta Saída para ter certeza

![image](https://user-images.githubusercontent.com/29258164/142488572-eebd91e5-ed1d-4687-9214-3c53dd8509ca.png)

![image](https://user-images.githubusercontent.com/29258164/142488348-41df0fa6-3139-4693-baf8-e8bed8c29373.png)

![image](https://user-images.githubusercontent.com/29258164/142488385-3e90e05d-87e3-4f47-a159-1b3eb03a726f.png)

![image](https://user-images.githubusercontent.com/29258164/142488617-d734a488-e7c2-490b-a50e-347b0fafa571.png)

**Comment by stefanimeneghetti** [comment]
Eu testei a integração com o Drive e ao que parece esta funcionando corretamente, talvez fosse algum bug relacionado a versão antiga que estava no ar. Usei um serviço que já estava aberto para testar e criei uma issue com o link para o serviço no playground para que assim o bot soubesse que já havia uma pasta criada para esse serviço:

![image](https://user-images.githubusercontent.com/51202548/157040136-cb622786-93c0-4292-8d33-9d3fb1394521.png)

Então a pasta antiga do serviço foi renomeada e adicionada como comentario na issue pelo bot:

![image](https://user-images.githubusercontent.com/51202548/157040266-fdb3e65f-e308-4e43-a65a-f23a734acb46.png)

Todos os arquivos adicionados pelo upload de arquivos do mural são enviados para a pasta da issue no drive e todos os arquivos adicionados nas pastas de entrada e saída aparecem para o solicitante por meio do mural.

![image](https://user-images.githubusercontent.com/51202548/157040469-b4e0e032-aa64-45ec-869a-aae9c72a07b0.png)

![image](https://user-images.githubusercontent.com/51202548/157040626-3a2e2be2-151a-4c15-859e-37b270bac261.png)

**Comment by CleissonVieira** [comment]
Acredito que de fato poderia ser isso, pois, existiam muitas alterações que não estavam em produção para o Mural V2.
@alissonpeloso Acho interessante levar isso para o pessoal em uma reunião de liderança. Esse é um assunto bastante comentado em reuniões passadas.
