### ISSUE TITLE
Tela de avaliação de solicitação

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#400]
Quando usuário acessa a página de avaliação do produto criado na solicitação e envia sua avaliação, é direcionado para a mesma página, porém sem conseguir interagir. (interessante informar que a avaliação foi realizada e direcionar para página da solicitação ou inicial)

**Comment by alissonpeloso** [comment]
Aonde fica essa tela de avaliação, @CleissonVieira?
