### ISSUE TITLE
Enviar notificação para o app quando há modificações na solicitação

### ISSUE THREAD

**Issue by stefanimeneghetti** [practice-uffs/mural#409]
Atualmente o App é capaz de receber push notifications através da API central, porém quando são feitas modificações nas solicitações o mural não está enviando notificações.

**Comment by CleissonVieira** [comment]
Fernando, estamos com dificuldades para realizar essa tarefa, precisamos da sua ajuda

**Comment by GuilhermeGraeff** [comment]
Continua na #374 (mesma situação)
