### ISSUE TITLE
Testar e validar

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#418]
Em reunião com @MilenaPaz2020 ela informou as seguintes situações no Mural V2:

1. Criando uma solicitação e vinculando a uma issue no github, ao realizar comentários na issue dentro do github com @cliente, esse comentário deveria ser refletido na tarefa do Mural. Porém, quando reflete demora horas para acontecer ou então não reflete.

2. As notificações não estão funcionando.

Objetivo: 
1. @stefanimeneghetti e @GuilhermeGraeff por gentileza tentem reproduzir estes problemas. Criem uma solicitação, vinculem a uma issue (pode ser do playground, ou como preferirem) e teste o @cliente, quanto tempo demora para refletir e se reflete. Marquei vocês dois para um representar o solicitante e outro o agente/atendente. Um de vocês deve ser removido como ADM do Mural V2. Vamos fazer o fluxo correto.

2. As notificações devem ser enviadas para quem solicitou. Validem se o teste de solicitante vai receber notificações de edições dentro da solicitação pelo agente/atendente.

**Comment by TaynaraCh** [comment]
Como comentei na reunião de lideres de ontem, o status da solicitação no mural parece não estar mudando para o cliente, acredito que tenha que ser conferido o que esta acontecendo e corrigir

**Comment by GuilhermeGraeff** [comment]
Bom dia, eu e a @stefanimeneghetti realizamos os testes hoje pela manhã.

As notificações referentes ao app do PRACTICE não funcionam, esperamos que isso seja corrigido na [issue](https://github.com/practice-uffs/mural/issues/374).

No e-mail, eu como cliente recebi as notificações quanto aos comentários realizados no serviço na issue referente no playground.

![image](https://user-images.githubusercontent.com/48657331/153862728-ec8c004f-99d3-4e41-8d61-c4c178b3efad.png)

**Comment by MilenaPaz2020** [comment]
> Bom dia, eu e a @stefanimeneghetti realizamos os testes hoje pela manhã.
> 
> As notificações referentes ao app do PRACTICE não funcionam, esperamos que isso seja corrigido na issue #374.
> 
> No e-mail, eu como cliente recebi as notificações quanto aos comentários realizados no serviço na issue referente no playground. E não houve atraso no recebimento dos e-mails.
> 
> Então, nossos testes com as notificações via e-mail funcionaram. Era algo mais específico?
> 
> ![image](https://user-images.githubusercontent.com/48657331/153862728-ec8c004f-99d3-4e41-8d61-c4c178b3efad.png)

Creio que era exatamente isso, @GuilhermeGraeff. Retornei agora de férias e percebi que os clientes estão interagindo e recebendo os comentários no mural.
