### ISSUE TITLE
Erro nos filtros / Status

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/mural#419]
**Descreva o bug/problema**
Os filtros não estão funcionando corretamente.

**Capturas de tela**
Sem filtros aplicados:
![Captura de Tela (5)](https://user-images.githubusercontent.com/71669689/152079086-93223046-5f51-4df2-b5e0-4b9739a9ac15.png)

Agora, aplicando o filtro de edição de vídeo. Observa-se que existem vários pedidos com a situação "em andamento", inclusive os pedidos de teste (que sugiro, serem todos excluídos). 
![Captura de Tela (6)](https://user-images.githubusercontent.com/71669689/152079085-e1c4ef54-5bbc-43af-a237-cc6a36042d89.png)

Agora, aplicando o filtro "em andamento" desaparecem todos os pedidos, mesmo aqueles que estão "em andamento".
![Captura de Tela (7)](https://user-images.githubusercontent.com/71669689/152079083-f7007a62-cb6f-4a6b-a562-376e7844996e.png)

Aplicando o filtro "cancelados" aparecem 3 pedidos que estão "em andamento". Nesse caso, o que está errado é a label "em andamento", pois estes 3 pedidos de fato foram cancelados no "gerenciamento interno", mas continuam com a situação "em andamento".
![Captura de Tela (8)](https://user-images.githubusercontent.com/71669689/152079374-a148e463-8cbd-460d-b351-7821a4439ebb.png)

E nesse caso, aplicando o filtro "na fila", aparece um pedido que, de fato, está na fila, porém, está com a situação "em andamento" (só visualmente).
![Captura de Tela (9)](https://user-images.githubusercontent.com/71669689/152079381-30c1b7f7-676e-4a21-997e-9ffb32e6fe99.png)

---
Não consigo concluir uma solicitação e alterar seu status para concluída (vejam que na imagem já esta escolhida a opção certa mas no aviso na lateral direita não é atualizado).

![image](https://user-images.githubusercontent.com/71669357/154151281-df6f3f3c-2670-4b51-b1a4-63aa8415e379.png)

**Comment by robisonjose** [comment]
Outra coisa que apareceu em relação aos filtros é o seguinte: 

Quando escolhemos qualquer categoria, aparecem título/local/datas/comentários/situação. Como o exemplo abaixo:

![Captura de Tela (12)](https://user-images.githubusercontent.com/71669689/152404496-bcd6ebf0-2cff-432b-8759-e10087d36889.png)
 
No entanto, quando colocamos na categoria "Transmissões ao vivo" só aparece o título. Como segue na imagem abaixo:
![Captura de Tela (10)](https://user-images.githubusercontent.com/71669689/152404654-6b099912-24b5-4633-adff-e39cb2259fc5.png)

**Comment by GuilhermeGraeff** [comment]
Certo @robisonjose, vamos investigar e atribuir a tarefa a algum dev assim que possível.

Sobre os pedidos testes, vamos identificar quais são testes e exclui-los.

**Comment by CleissonVieira** [comment]
@zorteaadriano Aguarda a solução da tarefa #426 para dar andamento nesta atividade.

Acredita-se que o problema dos filtros seja relacionado ao local onde alteramos o status do pedido, onde é mostrado o status para o cliente e o local onde o filtro está pegando esse dado para mostrar

**Comment by CleissonVieira** [comment]
> @zorteaadriano Aguarda a solução da tarefa #426 para dar andamento nesta atividade.
> 
> Acredita-se que o problema dos filtros seja relacionado ao local onde alteramos o status do pedido, onde é mostrado o status para o cliente e o local onde o filtro está pegando esse dado para mostrar

@zorteaadriano a tarefa foi solucionada. Pode-se dar andamento nessa issue.

**Comment by alissonpeloso** [comment]
@CleissonVieira, dá uma ajuda ao @zorteaadriano com esse problema

**Comment by CleissonVieira** [comment]
Realizei todos os testes possíveis e não identifiquei este problema com os filtros. 
Testei localmente o fluxo completo e também o Mural em produção com uma solicitação teste que tenho.
Editei para todos os status. O fluxo aconteceu perfeitamente, todos os locais que precisava atualizar o status assim aconteceu. Os filtros funcionaram com exatidão.

@alissonpeloso  O único detalhe é que hoje não temos filtro para o status "Em revisão pelo cliente", é necessário deixar em "qualquer" para encontrar estas solicitações. Não sei se tem motivo para não existir ou se apenas não foi criado.

Acredito que a situação reportada pelo @robisonjose se trata de solicitações antigas onde os filtros e status não estavam totalmente desenvolvidos, assim como o fluxo de pedidos. A pouco tempo foi atualizado o Mural V2 em produção. 
É valido finalizar essa tarefa e seguir com o uso. Caso ocorra novamente voltamos a revisar o fluxo e entender com um caso novo e atualizado.

**Comment by alissonpeloso** [comment]
@CleissonVieira, na reunião conversei com o @zorteaadriano e levante a possibilidade de ser um formato antigo de status que ficou no banco de dados. Talvez em alguma das atualizações foi alterado, pois o Adriano viu um status que não possuía aquele quadrinho. Como o status é só um text, teria que identificar se é esse o problema (conferindo no mural que está em produção), e tentar replicar localmente, criando uma solicitação com um nome diferente de status do que os já mapeados. Então, se confirmar, tentamos buscar no banco do mural em produção e alterar lá.

**Comment by alissonpeloso** [comment]
@CleissonVieira  e @zorteaadriano 

![image](https://user-images.githubusercontent.com/51202705/158243181-5fd4c22d-8921-469b-921c-704be0503379.png)

Ele está caindo nesse if sempre que o link do github está preenchido, como não foi testado com o link do github, não foi percebido. Estou corrigindo e commitando na branch.

**Comment by CleissonVieira** [comment]
Exatamente
Não realizei nenhum teste com link do github, não imaginei que o link influenciaria.
Perfeito, a situação era mais simples do que se imaginava.

Parabéns pelo trabalho hehe

**Comment by robisonjose** [comment]
> Realizei todos os testes possíveis e não identifiquei este problema com os filtros. Testei localmente o fluxo completo e também o Mural em produção com uma solicitação teste que tenho. Editei para todos os status. O fluxo aconteceu perfeitamente, todos os locais que precisava atualizar o status assim aconteceu. Os filtros funcionaram com exatidão.
> 
> @alissonpeloso O único detalhe é que hoje não temos filtro para o status "Em revisão pelo cliente", é necessário deixar em "qualquer" para encontrar estas solicitações. Não sei se tem motivo para não existir ou se apenas não foi criado.
> 
> Acredito que a situação reportada pelo @robisonjose se trata de solicitações antigas onde os filtros e status não estavam totalmente desenvolvidos, assim como o fluxo de pedidos. A pouco tempo foi atualizado o Mural V2 em produção. É valido finalizar essa tarefa e seguir com o uso. Caso ocorra novamente voltamos a revisar o fluxo e entender com um caso novo e atualizado.

Antigas quanto? Pois tem uma solicitação feita no dia 19/02/2022 às  (01:38) que está com esse problema que eu expliquei.

**Comment by robisonjose** [comment]
> Outra coisa que apareceu em relação aos filtros é o seguinte:
> 
> Quando escolhemos qualquer categoria, aparecem título/local/datas/comentários/situação. Como o exemplo abaixo:
> 
> ![Captura de Tela (12)](https://user-images.githubusercontent.com/71669689/152404496-bcd6ebf0-2cff-432b-8759-e10087d36889.png)
> 
> No entanto, quando colocamos na categoria "Transmissões ao vivo" só aparece o título. Como segue na imagem abaixo: ![Captura de Tela (10)](https://user-images.githubusercontent.com/71669689/152404654-6b099912-24b5-4633-adff-e39cb2259fc5.png)

Acho que uma nova versão foi ao ar e com ela esse problema voltou. @alissonpeloso

**Comment by alissonpeloso** [comment]
Ahh, acho que isso tá relacionado ao tamanho do título. É um problema da listagem, vou reabrir a issue para corrigir isso.
