### ISSUE TITLE
Problemas diversos

### ISSUE THREAD

**Issue by luizatonial** [practice-uffs/mural#425]
Não sei como anda as revisões do mural por parte da equipe de dev, não sei se todos os problemas já foram relatados ou não. Mas preferi ser repetitiva. CASO JÁ ESTEJA TUDO SENDO CORRIGIDO FAVOR IGNORAR A ISSUE. Percebi alguns problemas em alguns recursos básicos de conversa via mural:
---
- ~~Quando digitamos a mensagem no github e usamos o @cliente a mensagem não vai mais para o mural. No início demorava, agora simplesmente não vai. O contrário está funcionando, quando a mensagem é enviada via mural recebemos na issue.~~ **Testado recentemente, está ok**
---
- ~~Os arquivos enviados pelo solicitantes via mural, não vai para as pastas de entrada da issue associada.~~
- ~~Os arquivos introduzidos na pasta de saída não vão para a respectiva pasta no mural.~~
Tarefa Criada para envio de arquivos #398 
---
- ~~Os arquivos que eu envio, via mural ficam junto à descrição da pasta de entrada? eu achei que enviando pelo mural um produto pronto ele ficava na pasta de saída.~~
**A intenção é nós trabalharmos através do github. Então produto pronto deve ser atualizado pelo github nesse primeiro momento, inserido diretamente na pasta saída. O mural é para o cliente inserir documentos na pasta entrada**
---
- ~~Como o @robisonjose já comentou em uma issue, temos problemas com filtros, algumas vezes as descrições ou os serviços desaparecem.~~
- ~~Não consigo concluir uma solicitação e alterar seu status para concluída (vejam que na imagem já esta escolhida a opção certa mas no aviso na lateral direita não é atualizado).~~
**Tarefa Criada para filtro e status se trata do mesmo problema** #419 
---

![image](https://user-images.githubusercontent.com/71669357/154151281-df6f3f3c-2670-4b51-b1a4-63aa8415e379.png)
@practice-uffs/dev

**Comment by luizatonial** [comment]
além da questão da inclusão das perguntas e envio de arquivos referentes aos nossos formulários que já estão sendo averiguados e a possibilidade de exclusão dos inúmeros testes das lives que dificultam o entendimento. Já que não consigo cancelar ou encerrar as solicitações de teste ou concluidas.

**Comment by luizatonial** [comment]
uma coisa nadave que eu lembrei... por que eu não consigo acessar o mural na rede da UFFS?

**Comment by CleissonVieira** [comment]
> além da questão da inclusão das perguntas e envio de arquivos referentes aos nossos formulários que já estão sendo averiguados e a possibilidade de exclusão dos inúmeros testes das lives que dificultam o entendimento. Já que não consigo cancelar ou encerrar as solicitações de teste ou concluidas.

Acredito que essa questão deveria ser resolvida com os filtros, onde não busca pelas solicitações já concluídas. Nesse primeiro momento da para passar os testes como concluído.

**Comment by CleissonVieira** [comment]
@luizatonial editei sua descrição comentando cada item que citou. Informando tarefa se já existe ou se já foi resolvido.
Em todos os casos ainda não estão em produção, estamos atualizando a versão que está disponível para público.

**Comment by CleissonVieira** [comment]
> > > além da questão da inclusão das perguntas e envio de arquivos referentes aos nossos formulários que já estão sendo averiguados e a possibilidade de exclusão dos inúmeros testes das lives que dificultam o entendimento. Já que não consigo cancelar ou encerrar as solicitações de teste ou concluidas.
> > 
> > 
> > Acredito que essa questão deveria ser resolvida com os filtros, onde não busca pelas solicitações já concluídas. Nesse primeiro momento da para passar os testes como concluído.
> 
> Se eu não me engano, também não está dando pra mudar a situação das solicitações. Não consegui testar pra ver se é isso mesmo pois a parte dos pedidos no admin ainda não estão funcionando.

O que seria a situação? Quer dizer status? Talves a mesma situação que a Luiza descreveu no último item da descrição desta issue @robisonjose ?

**Comment by robisonjose** [comment]
Pelo que entendi sim, seria a mudança de "finalizado", "cancelado", "em andamento". Acho que além de não dar pra mudar, elas não seguem os filtros, mas só acho, não lembro bem, teria que testar.

**Comment by luizatonial** [comment]
> Pelo que entendi sim, seria a mudança de "finalizado", "cancelado", "em andamento". Acho que além de não dar pra mudar, elas não seguem os filtros, mas só acho, não lembro bem, teria que testar.

comigo acontece isso, não funciona.

**Comment by luizatonial** [comment]
Obrigada pela atenção @CleissonVieira 😉😉
