### ISSUE TITLE
Bug ao deletar usuário

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#426]
- O próprio usuário se deletou
![image](https://user-images.githubusercontent.com/29258164/154336729-261738e8-5f0e-4a92-ab70-7b3585b05bf7.png)

- Com o passo acima aconteceu logoff da conta. Informando mesmo login e senha, criou o usuário novamente. Em seguida criou um pedido como user normal (cliente).

- Quando um user Administrador tentou acessar a tela de pedidos gerou o seguinte erro: 

![image](https://user-images.githubusercontent.com/29258164/154285760-0dc60662-7a91-4cfb-b45c-db80c01a2b70.png)

Acredita-se que o problema seja porque o usuário, antes de se deletar, tinha pedidos vinculados a sua conta.

**Comment by CleissonVieira** [comment]
Foi verificado que a versão do Mural V2 em produção está desatualizada.
O botão de apagar usuários não existe mais, assim como outros detalhes.
Com isso eu vejo que deletando os pedidos vinculados ao cleisson.raimundi e atualizando o Mural em Produção para a branch V2 do github resolveria este problema e evitaria que o mesmo voltasse a acontecer

**Comment by alissonpeloso** [comment]
Eu vou tentar reproduzir o erro no localhost, mas pelo que vi, essa versão usa o PHP antigo. Se conseguir algo, eu comento aqui

**Comment by alissonpeloso** [comment]
O @Dovyski ajustou o mural que está em produção :)

Fechando issue
