### ISSUE TITLE
Mural V2 não carrega na rede da UFFS

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#428]
Foi reportado que não é possível acessar o Mural na rede na UFFS.
É necessário verificar, pois, a plataforma foi criada com o principal objetivo de atender as demandas na universidade.

**Comment by alissonpeloso** [comment]
Ticket aberto ao TI: https://ati.uffs.edu.br/customer.pl?Action=CustomerTicketZoom;TicketNumber=2022030332000085

**Comment by luizatonial** [comment]
vi que essa issue ainda ta aberta e aqui em Erechim funciona agora, o TI arrumou td... não sei como ta no resto
