### ISSUE TITLE
Ajustar tela de acompanhar serviços (possui scroll horizontal)

### ISSUE THREAD

**Issue by stefanimeneghetti** [practice-uffs/mural#440]
Quando vista no formato mobile a tela de acompanhar serviços possui um scroll horizontal. Esse mesmo scroll se apresenta mesmo na versão desktop caso o titulo da solicitação seja extenso.

**Comment by alissonpeloso** [comment]
@stefanimeneghetti, não esquece de atribuir a issue no sprint

**Comment by alissonpeloso** [comment]
@stefanimeneghetti, como tá a situação da tarefa?

**Comment by stefanimeneghetti** [comment]
Tá quase pronto, eu tive um pouco de dificuldade de organizar os itens da forma que eu queria mas agora acho que consegui então é só fazer alguns ajustes de espaçamento e se isso não quebrar mais nada ta vai estar pronto.
