### ISSUE TITLE
Situação com mural.tests

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#455]
Ao realizar tarefas veio a necessidade de utilizar o [Mural de teste](http://mural.tests.practice.uffs.cc/) para verificar envio de anexos para o drive e mensagens para o github através do Mural, e vice-versa. Porém, esses fluxos não estão em funcionamento para o Mural Teste.

Em conversa com @alissonpeloso tentamos rodar ```php-8.0 artisan queue:work nohup``` no ssh onde o Mural Teste está alocado. 
Segue, na imagem abaixo, o erro retornado:

![image](https://user-images.githubusercontent.com/29258164/161407479-977c2de0-fe48-40c8-88f8-9abd36621d9d.png)

**Comment by alissonpeloso** [comment]
![image](https://user-images.githubusercontent.com/51202705/161531554-0159475e-68c7-4f2f-935d-04a405caebcf.png)

A parte do git não funciona pois não temos configurado essas credenciais aqui. Teria que ver com o Fernando qual é a configuração do mural em prod.

**Comment by alissonpeloso** [comment]
A parte do work foi ajustada, tinha te passado o comando errado, @CleissonVieira . O correto é:
```
nohup php-8.0 artisan queue:work --daemon &
```

**Comment by alissonpeloso** [comment]
As credenciais do git hub foram inseridas no mural de testes
