### ISSUE TITLE
Ajustar página de ideias no mobile

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/mural#467]
Na versão mobile, há alguns problemas de layout na página de ideias do mural:

- [ ] O texto ao lado da lâmpada fica muito apertado. Talvez dê para diminuir o tamanho e mudar a disposição no mobile. Note que os itens de ideias acabam voando por cima do texto em alguns momentos.
![image](https://user-images.githubusercontent.com/51202705/164236756-c3dd00cd-973b-40d0-9466-74c27f2ee9ae.png)

- [ ] Outro problema é o formulário de ideia. Podemos aumentar a sua largura no mobile para não ficar tão estreito e centralizar o botão de "ENVIAR".
![image](https://user-images.githubusercontent.com/51202705/164237343-96782d7b-e464-4e64-b9f3-ecf88a857fc0.png)

**Comment by alissonpeloso** [comment]
A parte do formulário, pode se basear no formulário da página de feedback que também possuía o mesmo problema @patitrev

**Comment by patitrev** [comment]
As mudanças estão na branch 467;

**Comment by alissonpeloso** [comment]
@patitrev, lembre que precisa criar PR para a issue e deve colocá-la a label "Need Review" na issue. Só podemos mudar o estado da isse para "pronto" depois que foi dado merge da branch da issue com a dev.
