### ISSUE TITLE
Ajustar informação de última modificação e arquivos inseridos em solicitações para nome do usuário/PRACTICE 

### ISSUE THREAD

**Issue by CleissonVieira** [practice-uffs/mural#471]
Verificar se existe a possibilidade de configurar a integração do drive com a conta do PRACTICE.

Se for possível, então será necessário criar um script para verificar quando um usuário solicitante realizar um upload de arquivo na solicitação, para inserir o nome dele como informação desse upload. 
Caso essa integração não seja possível, ajustar esse script e verificar quando não se trata do usuário solicitante realizando o upload, logo é a equipe do PRACTICE, então inserir o nome PRACTICE como informação do upload.

**Comment by alissonpeloso** [comment]
Acredito que como o google drive no mural é um iframe, não vamos conseguir alterar o nome via script. É um caso parecido com o iframe do maps no app boas-vindas

**Comment by alissonpeloso** [comment]
![image](https://user-images.githubusercontent.com/51202705/171438029-e6ce0e32-456c-4951-b499-87dccc3b8fd8.png)

**Comment by alissonpeloso** [comment]
aqui funcionou, acredito que apenas fazendo isso, resolva

**Comment by alissonpeloso** [comment]
Vou fazer no mural de produção

**Comment by alissonpeloso** [comment]
Não consegui permissão para mover o arquivo de `credentials.json` para o servidor, aguardando a resposta do pessoal do TI.

**Comment by alissonpeloso** [comment]
Consegui alterar o arquivo no mural de produção, porém a queue do drive parou de funcionar por algum motivo. Acredito que tenha que liberar alguma URL de direcionamento.

**Comment by alissonpeloso** [comment]
Done!  :D
![image](https://user-images.githubusercontent.com/51202705/172377542-a11cfa36-9067-42c1-bf5f-c081c168d4c5.png)
