### ISSUE TITLE
Testar mural de testes

### ISSUE THREAD

**Issue by stefanimeneghetti** [practice-uffs/mural#481]
O mural que está rodando em produção está bastante desatualizado com relação ao que está rodando no mural de testes. O objetivo dessa issue é testar o mural em execução na url: http://mural.tests.practice.uffs.cc/ e ver se está tudo funcionando como deveria para que seja possível atualizar o mural de produção para uma versão mais recente.

Listagem de bugs encontrados:

- [ ] Quando adiciona mais de uma label `mural:<algo>` o bot remove todas as labels (não sei como resolver, pois é disparado um evento pra cada "labeled", então são tratados simultanemente.
- [x] #491
- [x] #489

**Comment by alissonpeloso** [comment]
## Elencando novas funções para o pessoal do Practice testar:

- Limite de tentativas de Login
- Bugs de perguntas adicionais
- Melhoras visuais
- Excluir e Editar comentário
- Alterar status de pedido através da label (após vincular uma issue na solicitação, basta usar as tags `mural:algumacoisa` para mudar o status, testar usando [playground](https://github.com/practice-uffs/playground)).
- Alterar status de uma solicitação no mural que está vinculado à uma issue no github irá atualizar a label automaticamente (testar usando [playground](https://github.com/practice-uffs/playground))
