### ISSUE TITLE
Problema com o token do Google que caí direto

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/mural#512]
Verificar por que o token do google caí com tanta frequência, antigamente não era assim. Acredito que tenha alguma configuração para ajustar isso

**Comment by alissonpeloso** [comment]
Mandei mensagem para o Fernando, acredito que ela possa ajudar.

**Comment by zorteaadriano** [comment]
atualização: alterei o status de publicação do app no console do google para 'em produção', seguindo a dica que encontrei pesquisando um pouco mais no link abaixo: https://stackoverflow.com/questions/69459141/how-to-fix-google-tokens-expiring-after-seven-days
