### ISSUE TITLE
Criar filtros para a visualização das solicitações por ordem cronológica

### ISSUE THREAD

**Issue by alissonpeloso** [practice-uffs/mural#519]
A ideia dessa tarefa é possibilitar que os serviços do painel de administração do mural permitam que as solicitações sejam dispostas na ordem cronológica de criação ou de interação:

![image](https://user-images.githubusercontent.com/51202705/192603045-c38f883d-6a2d-4074-ae29-572d36877b7a.png)

Assim, é possível visualizar as mais recentes. Acho que poderia ser aplicado como a visualização de um filtro nas planilhas do google ou excel.

**Comment by zorteaadriano** [comment]
@gustavoSutil como está indo com a tarefa? se precisar de algo pode me chamar ou postar aqui.

**Comment by zorteaadriano** [comment]
@gustavoSutil

Eu percebi que você havia tentado fazer uma nova busca na função que filtra as datas, mas na verdade se fizermos dessa forma, os outros filtros seriam desconsiderados, por isso é feito a busca de todos os dados na linha 124 e depois são aplicados os filtros e ordenações.

Precisa haver alguma forma de filtrar as datas dos comentários diretamente na query já montada, algo parecido com isso:
(adicionei o 'comments.created_at', porém assim não está funcionando mas precisa ser algo parecido com isto)

![image](https://user-images.githubusercontent.com/74692811/210245626-d3911a1c-fa45-4141-81e5-bba78c94139a.png)

**Comment by gustavoSutil** [comment]
Para resolver o problema, dentro do model orders tentei acessar o atributo que relacionava o objeto com comments nesse trecho de código, da mesma forma que estava feito, com order by:
![image](https://user-images.githubusercontent.com/85875309/210376462-1c7e66b1-eb4e-4142-86f3-4044df4d17dd.png)
Para isso primeiro criei uma variável para servir no liveware:
`       public array $sort_by_date;
`
Depois criei a parte do front, que ficou assim:
![image](https://user-images.githubusercontent.com/85875309/210376852-8dd73876-acb2-4618-bf61-9e319c0de020.png)
As opções de ordenação foram:
![image](https://user-images.githubusercontent.com/85875309/210376942-9dc99665-2a71-496b-8797-a9ffde5666d0.png)
Por fim alterei a função findOrders criando mais uma função:
![image](https://user-images.githubusercontent.com/85875309/210377242-7d2a5828-2e54-4499-a0c0-87a24a93c14f.png)
O resultado foi esse:
![unnamed](https://user-images.githubusercontent.com/85875309/210378234-c2ae4942-027c-47a4-9ee2-0a6f5845ff96.png)
Porém quando alteramos para ordenar por último comentário, aparece o erro:
Illuminate\Database\QueryException
SQLSTATE[HY000]: General error: 1 no such column: comments.created_at (SQL: select * from "orders" order by "comments"."created_at" desc limit 50 offset 0)
Isso porque o order by vai procurar um atributo com esse nome, ele não existe ainda. Ele só vai ser criado após essa linha:
`           $this->orders = $query->paginate($this->paginationAmount);
`
que vai se transformar em uma collection após a consulta. 
Com essa linha:
`
      $this->orders = $query->paginate($this->paginationAmount);
      dd($this->orders);
`
 o resultado será esse:
![image](https://user-images.githubusercontent.com/85875309/210379077-06514a3c-1f09-4d65-9ad6-82a8137e222c.png)
repare que dentro de items, relations existe outra collection comments.
colocando isso no dd (no caso irei colocar o primeiro resultado da pagina-index 0):
`
           dd($this->orders[0]['comments']);
`
 temos:
![image](https://user-images.githubusercontent.com/85875309/210379500-2a16757c-1dfe-41bc-904c-9296404893f5.png)
que são os comentários feitos na order de index 0.
Com isso é possível concluir que:
-Não é possível acessá-los com o order by pois ele não entra no escopo do SQL.
Para conseguir fazer orders se relacionar com os comments é necessário criar um join, escolhi o left join. E ficou assim:
![image](https://user-images.githubusercontent.com/85875309/210379718-729d32d2-8bf1-4860-9b12-a8335b57fa59.png)
E então os cards ficaram ordenados por ordem de criação, o único problema é que para cada comentário criou-se um card de pedido, assim o-fazendos duplicados no caso de mais de um pedido.
Isso poderia ser resolvido com uma subquery SQL,exemplo:
`SELECT 
	orders.*,
	comments.commentable_id AS id_c,
	comments.created_at AS commentable_created
	FROM 
		orders LEFT JOIN comments 
		WHERE id_c = orders.id 
		AND NOT EXISTS(
			SELECT comments.*
			FROM comments 
			WHERE comments.commentable_id = id_c 
			AND 
			commentable_created > comments.created_at
		);`
Porém não consegui fazer com as ferramentas do eloquent, ficando então, com os pedidos repetidos na view.
