### ISSUE TITLE
Adicionar filtros na listagem de usuários

### ISSUE THREAD

**Issue by zorteaadriano** [practice-uffs/mural#527]
Com o problema que estamos tendo no envio de e-mails (#526), tive dificuldade em buscar o usuário que relatou o problema para verificar as informações dele, tive que ir página por página até encontrar o usuário e verificar se tudo estava correto. 

Seria interessante ter algum filtro por nome, email ou tipo de usuário (admin ou normal) para facilitar caso haja necessidade de verificar as informações de algum usuário (pode seguir o padrão dos filtros na página de pedidos).

![image](https://user-images.githubusercontent.com/74692811/203353103-5729c80f-2643-4f51-9509-3c5ff1d48767.png)

**Comment by zorteaadriano** [comment]
@demostheneromane, como vai a tarefa? se precisar de algo pode me chamar ou comentar aqui.

**Comment by demostheneromane** [comment]
o layout da pagina usuário 

![2022-12-08 (24)](https://user-images.githubusercontent.com/92757855/206389100-997dc159-58be-4270-bd87-d8a2241cca92.png)

**Comment by zorteaadriano** [comment]
@demostheneromane se puder fazer o  commit com suas alterações, gostaria de revisar o código para nos encaminharmos para finalizar essa issue.

**Comment by demostheneromane** [comment]
**adicionei o filtro !** 

![Captura de Tela (2)](https://user-images.githubusercontent.com/92757855/210920085-4d3c4b08-5c21-4b28-b3dd-f18dbc7cb03f.png)

![Captura de Tela (3)](https://user-images.githubusercontent.com/92757855/210920234-b81fad1e-4c02-4ecb-8d75-290704352283.png)

![Captura de Tela (4)](https://user-images.githubusercontent.com/92757855/210920324-dae82792-fd3c-401f-a9d5-fb51b6b95161.png)
