### ISSUE TITLE
Exibir contato do PRACTICE por whatsapp para usuários logados.

### ISSUE THREAD

**Issue by zorteaadriano** [practice-uffs/mural#528]
Adicionar no canto inferior direito um ícone do whatsapp, que, ao clicar, leva para o contato principal da equipe do practice.

Obs: exibir somente para usuários logados no mural.

Número de whatsapp do practice: +55 42 3635-0038.

Origem dessa necessidade:

        A minha sugestão é que fosse informado em algúm lugar no mural, o número do whatsapp do PRACTICE, visto que muitos solicitantes acabam entrando em contato no whatsapp privado de alguns bolsistas, assim como devia ter um campo para o solicitante deixar o contato dele no momento que faz a solicitação, pois somente no formulário de lives é pedido o contato do solicitante.

_Originally posted by @MariaLuizaReviliau in https://github.com/practice-uffs/programa/issues/1352#issuecomment-1322844385_

**Comment by zorteaadriano** [comment]
@andregiachini você precisa só ter um cuidado pois já tem um ícone neese local que ao clicar leva o usuário de volta ao topo, então tem que buscar uma forma que fique bonito mesmo contendo os dois ícones naquela região.

**Comment by zorteaadriano** [comment]
![image](https://user-images.githubusercontent.com/74692811/204871670-4e65e59c-155c-4814-a2e5-776af89236ea.png)

Acredito que um balão semelhante à esse com o ícone do whatsapp seria suficiente. Era algo assim que esperava 
@MariaLuizaReviliau?

**Comment by andregiachini** [comment]
![image](https://user-images.githubusercontent.com/56172743/206210167-28b497a5-36c3-4f27-88dd-0c738af7a30e.png)
![image](https://user-images.githubusercontent.com/56172743/206210280-91a0e879-b07d-4800-88db-c2244c10533f.png)

Algo assim que era esperado ou necessita alguma mudança?

**Comment by MariaLuizaReviliau** [comment]
Está perfeito! Muito Obrigadaaa
