### ISSUE TITLE
BUG: Problema na filtragem quando a página atualiza.

### ISSUE THREAD

**Issue by robisonjose** [practice-uffs/mural#538]
Passo a passo: 

1. Entro em: Admin > Pedidos;
2. Seleciono "Status do Pedido: Finalizado";
3. São tantas tarefas, que elas ficam divididas em duas páginas;
4. Clico para ir para a segunda página, para ver o resto das tarefas finalizadas;
5. Site atualiza e volta para o "default" (status do pedido: qualquer)

Sempre que a gente clica para ir para a próxima página de solicitações, o site atualiza e volta para a filtragens iniciais (todos/qualquer).

**Comment by robisonjose** [comment]
"Problema" aleatório que encontrei: 

https://practice.uffs.edu.br/mural/servico/13
https://practice.uffs.edu.br/mural/servico/9

não abrem corretamente. não que isso faça alguma diferença, mas talvez seja importante vocês saberem que isso existe (sei lá).

**Comment by zorteaadriano** [comment]
@robisonjose pelo que vi os pedidos 13 e 09 são somente de teste e estão com alguma informação faltando, são pedidos antigos, vou removê-los pra evitar aparecer esse erro.

Paginação dos pedidos após aplicar filtros:  já percebemos esse probelma e estamos tentando resolver na issue que adiciona o filtro de ordem cronológica (#519), e o mesmo ocorre na listagem de usuários. Não foi encontrado uma solução ainda, acredito que podemos deixar essa issue e pra resolver esse problema de forma separada aos ajustes nos filtros.

**Comment by robisonjose** [comment]
Se for tranquilo de fazer, daria para remover todas as solicitações de testes? Elas poluem um pouco o mural

**Comment by zorteaadriano** [comment]
@robisonjose criei uma issue pra criar um botão 'remover' na tela de listagem das solicitações, mas vou remover essas manualmente por enquanto.

**Comment by robisonjose** [comment]
essa issue foi concluida? @zorteaadriano

**Comment by zorteaadriano** [comment]
@robisonjose, o @andregiachini retomou a tarefa, estamos trabalhando isso na issue #519.
