### ISSUE TITLE
Ajustes para solicitações do estúdio

### ISSUE THREAD

**Issue by zorteaadriano** [practice-uffs/mural#548]
Adicionar documento presente na pasta: https://drive.google.com/drive/folders/1vziGvKsOV0UA__AHFoC3E-cWmW-_Rra_

O documento precisa aparecer no seguinte local: abaixo do termo já existente, no formato de um checkbox que seja validado na submissão do formulário.

![image](https://user-images.githubusercontent.com/74692811/223841202-42a5fd13-7c07-4301-8ba2-f2d52c329eed.png)

Seria interessante salvar na categoria da solicitação (/gerenciar/categorias) o link e a frase que vai exibir no checkbox do termo e fazer o controle na página para exibir quando houver link preenchido.

**Comment by andregiachini** [comment]
Adição à issue: adicionar um campo para o link da Agenda do Google na categoria da solicitação (/gerenciar/categorias)

**Comment by andregiachini** [comment]
Vídeo demonstrando como funciona 
https://user-images.githubusercontent.com/56172743/225646879-d6781e75-00ec-4549-95cf-9898d6ca711f.mp4
