### ISSUE TITLE
[REFACTOR: reações] Mudar a estratégia de criação de reações

### ISSUE THREAD

**Issue by jeanchilger** [practice-uffs/mural#61]
Atualmente, sempre que uma nova reação é criada, é realizada uma nova requisição, e toda vez todas as reações são iteradas para saber se o usuário criou alguma delas. Esta estratégia foi adotada devido à falta de conhecimentos, todavia ela é muito custosa e há diversas outras abordagens que podem ser adotadas no lugar, aumento a velocidade de criação/exclusão de reações.

**Comment by Dovyski** [comment]
As reações foram removidas no mural `v2`.
