### ISSUE TITLE
[Discussão] O que fazer quando um item é criado

### ISSUE THREAD

**Issue by jeanchilger** [practice-uffs/mural#91]
Quando um Serviço e um Feedback são criados, ocorrem comportamentos distintos: para serviço uma mensagem é mostrada, e para feedback nada ocorre (:sob:). Poderíamos ajustar isto, por isso criei esta issue, no intuito de agruparmos algumas sugestões.

A minha sugestão (até então) é fechar o modal de criação e mostrar um _popup_ com a mensagem de item criado. Neste caso o _loader_ poderia aparecer antes do _popup_ ou no próprio _popup_.

**Comment by arufonsekun** [comment]
Achei a sugestão interessante e acho válido implementarmos.

**Comment by Dovyski** [comment]
Eu gosto da ideia de fechar o modal, mas não de colocar um popup com a mensagem. Uma melhor UX seria fechar o modal e mostrar o card de ideia recém criado no começo da lista, com alguma animação de fadein nele. Em teoria isso não deve ser difícil de fazer, imaginando que podemos fechar o modal, atualizar a lista, e apenas adicionar uma classe de CSS no card recém criado (que temos a informação).

[Essa](https://animate.style/) biblioteca deve ajudar bastante com o trabalho.
